export const internalLinkRules: Record<string, string[]> = {
  '/': ['/features', '/pricing', '/demo', '/security'],
  '/about': ['/features', '/demo', '/contact'],
  '/contact': ['/demo', '/pricing', '/security'],
  '/careers': ['/about', '/contact', '/demo'],
  '/features': ['/pricing', '/demo', '/security', '/trust-center'],
  '/features/case-management': ['/features/document-automation', '/features/client-portal', '/demo'],
  '/features/document-automation': ['/features/case-management', '/features/legal-ai', '/demo'],
  '/features/billing-time-tracking': ['/features/trust-accounting', '/pricing', '/demo'],
  '/features/trust-accounting': ['/trust-center', '/features/billing-time-tracking', '/demo'],
  '/features/client-portal': ['/features/case-management', '/security', '/demo'],
  '/features/analytics-reporting': ['/features/billing-time-tracking', '/solutions/mid-size-law-firms', '/demo'],
  '/features/legal-ai': ['/features/document-automation', '/trust-center', '/demo'],
  '/solutions': ['/solutions/solo-law-firms', '/solutions/small-law-firms', '/solutions/mid-size-law-firms'],
  '/solutions/solo-law-firms': ['/features/case-management', '/pricing', '/demo'],
  '/solutions/small-law-firms': ['/features/analytics-reporting', '/features/trust-accounting', '/demo'],
  '/solutions/mid-size-law-firms': ['/integrations', '/trust-center', '/demo'],
  '/integrations': ['/demo', '/features', '/trust-center'],
  '/resources': ['/blog', '/demo', '/contact'],
  '/blog': ['/resources', '/features/legal-ai', '/demo'],
  '/pricing': ['/demo', '/features', '/security'],
  '/demo': ['/pricing', '/features', '/trust-center'],
  '/security': ['/trust-center', '/features', '/demo'],
  '/trust-center': ['/security', '/features', '/demo'],
  '/privacy': ['/trust-center', '/security', '/'],
  '/docs': ['/features', '/demo', '/'],
};
